name = "nba-ai-agent"
main = "dist/index.js"
compatibility_date = "2025-12-22"
type = "javascript"

[ai]
binding = "AI"

[build]
command = "npm run build"
upload_format = "modules"

[[kv_namespaces]]
binding = "NBA_MEMORY"
id = "65811f1e37504c58957deb32c4844fcb"
preview_id = "e5a5b42954f94348a05358b8c0f9e0f5"


[triggers]
crons = ["* * * * *"]

[assets]
directory = "./public"
