name = "nba-ai-agent"
main = "src/index.ts"
compatibility_date = "2025-12-22"
type = "javascript"

[ai]
binding = "AI"                       # enables workers AI

[build]
upload_format = "modules"

[triggers]
crons = ["* * * * *"]
